/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacaograficaarraylistnoite;

import biblioteca.Bebida;
import biblioteca.BebidaDAO;
import biblioteca.Doce;
import biblioteca.DoceDAO;
import biblioteca.Usuario;
import biblioteca.UsuarioDAO;
import javax.swing.ImageIcon;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        //Inserindo Doces
        DoceDAO.inserir(new Doce("Bolo de chocolate", 18, "2kg"));
        DoceDAO.inserir(new Doce("Bolo de laranja", 15, "2kg"));
        DoceDAO.inserir(new Doce("Bolo de baunilha", 20, "2kg"));
        DoceDAO.inserir(new Doce("Torta de nozes", 30, "2kg"));
        DoceDAO.inserir(new Doce("Torta de maçã", 40, "2kg"));
        DoceDAO.inserir(new Doce("Torta de limão", 35, "2kg"));
        DoceDAO.inserir(new Doce("Brigadeiro", 3, "2kg"));
        DoceDAO.inserir(new Doce("Beijinho", 3, "2kg"));
        DoceDAO.inserir(new Doce("Cajuzinho", 3, "2kg"));
        DoceDAO.inserir(new Doce("Empada doce", 4, "2kg"));
        DoceDAO.inserir(new Doce("Pavê de morango", 35, "2kg"));
        DoceDAO.inserir(new Doce("Mousse de chocolate", 10, "2kg"));
        DoceDAO.inserir(new Doce("Mousse de maracujá", 10, "2kg"));
        DoceDAO.inserir(new Doce("Arroz doce", 25, "2kg"));
        DoceDAO.inserir(new Doce("Canjica", 25, "2kg"));
        
        //Inserindo Bebidas
        BebidaDAO.inserir(new Bebida("Água com gás", 3f, "500ml"));
        BebidaDAO.inserir(new Bebida("Água sem gás", 4f, "500ml"));
        BebidaDAO.inserir(new Bebida("Mate", 3.5f, "300ml"));
        BebidaDAO.inserir(new Bebida("Coca-Cola", 8f, "2L"));
        BebidaDAO.inserir(new Bebida("Coca-Cola Zero", 10f, "2L"));
        BebidaDAO.inserir(new Bebida("Guaraná", 7f, "2L"));
        BebidaDAO.inserir(new Bebida("Suco de limão", 3.5f, "300ml"));
        BebidaDAO.inserir(new Bebida("Suco de uva", 3.5f, "300ml"));
        BebidaDAO.inserir(new Bebida("H2O", 4f, "300ml"));
        BebidaDAO.inserir(new Bebida("Guaravita", 2.5f, "300ml"));
        
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon("D:\\Documents\\Alessandra\\Codigo_Ana\\V2\\AplicacaoGraficaArrayListNoite\\src\\Image\\icon.jpeg");
        this.setIconImage(img.getImage());
        
        Usuario usuarioLogado = UsuarioDAO.getUsuarioLogado();
        if (usuarioLogado != null)
            boasVindasLabel.setText(String.format("Bem vindo(a), %s!", usuarioLogado.getNome()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        boasVindasLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        docesItem = new javax.swing.JMenuItem();
        bebidasItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        carrinhoItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        sairItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);
        setSize(new java.awt.Dimension(361, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.jpeg"))); // NOI18N

        boasVindasLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boasVindasLabel.setText("Bem vindo, João!");

        jMenu1.setText("Produtos");

        docesItem.setText("Doces");
        docesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docesItemActionPerformed(evt);
            }
        });
        jMenu1.add(docesItem);

        bebidasItem.setText("Bebidas");
        bebidasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidasItemActionPerformed(evt);
            }
        });
        jMenu1.add(bebidasItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Carrinho de compras");

        carrinhoItem.setText("Carrinho de compras");
        carrinhoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrinhoItemActionPerformed(evt);
            }
        });
        jMenu2.add(carrinhoItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");

        sairItem.setText("Sair");
        sairItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairItemActionPerformed(evt);
            }
        });
        jMenu3.add(sairItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boasVindasLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boasVindasLabel)
                .addGap(0, 149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairItemActionPerformed

    private void docesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docesItemActionPerformed
        TelaDoces telaDoces = new TelaDoces();
        telaDoces.setVisible(true);
    }//GEN-LAST:event_docesItemActionPerformed

    private void bebidasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidasItemActionPerformed
        TelaBebidas telaBebidas = new TelaBebidas();
        telaBebidas.setVisible(true);
    }//GEN-LAST:event_bebidasItemActionPerformed

    private void carrinhoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrinhoItemActionPerformed
        TelaCarrinho telaCarrinho = new TelaCarrinho();
        telaCarrinho.setVisible(true);
    }//GEN-LAST:event_carrinhoItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bebidasItem;
    private javax.swing.JLabel boasVindasLabel;
    private javax.swing.JMenuItem carrinhoItem;
    private javax.swing.JMenuItem docesItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem sairItem;
    // End of variables declaration//GEN-END:variables
}
