/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacaograficaarraylistnoite;

import biblioteca.Bebida;
import biblioteca.BebidaDAO;
import biblioteca.Carrinho;
import biblioteca.ProdutoCarrinho;
import biblioteca.Usuario;
import biblioteca.UsuarioDAO;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class TelaCarrinho extends javax.swing.JFrame {

    /**
     * Creates new form TelaCarrinho
     */
    public TelaCarrinho() {
        initComponents();
        atualizarLista();
        this.setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon("D:\\Documents\\Alessandra\\Codigo_Ana\\V2\\AplicacaoGraficaArrayListNoite\\src\\Image\\icon.jpeg");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCarrinho = new javax.swing.JList<>();
        removerButton = new javax.swing.JButton();
        finalizarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        atualizarButton = new javax.swing.JButton();
        quantidadeLabel = new javax.swing.JLabel();
        menosButton = new javax.swing.JButton();
        maisButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carrinho");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carrinho de compras");

        listaCarrinho.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaCarrinho.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaCarrinhoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaCarrinho);

        removerButton.setText("Remover item");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        finalizarButton.setText("Finalizar compra");
        finalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quantidade");

        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalLabel.setText("Total: R$180");

        atualizarButton.setText("Atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        quantidadeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantidadeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidadeLabel.setText("1");

        menosButton.setText("-");
        menosButton.setEnabled(false);
        menosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosButtonActionPerformed(evt);
            }
        });

        maisButton.setText("+");
        maisButton.setEnabled(false);
        maisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(menosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(maisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(removerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finalizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(atualizarButton)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removerButton)
                            .addComponent(finalizarButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantidadeLabel)
                            .addComponent(menosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarButtonActionPerformed
        Usuario usuario = UsuarioDAO.getUsuarioLogado();
        JOptionPane.showMessageDialog(null, String.format("Obrigado pela preferência!\n"
                + "Seu total é R$%.2f\n"
                + "Suas compras serão enviadas para o endereço:\n"
                + "%s, %s - %s", Carrinho.getValorTotal(), usuario.getEndereco(), usuario.getNumero(), usuario.getCep()));
        Carrinho.limpar();
        atualizarLista();
    }//GEN-LAST:event_finalizarButtonActionPerformed

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        atualizarLista();
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        try {
            int id = getIdSelecionado();
            Carrinho.removerId(id);
            atualizarLista();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um item.");
        }
    }//GEN-LAST:event_removerButtonActionPerformed

    private void listaCarrinhoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaCarrinhoValueChanged
        try {
            int id = getIdSelecionado();
            int quantidade = Carrinho.getQuantidade(id);
            quantidadeLabel.setText(String.valueOf(quantidade));
            maisButton.setEnabled(true);
            menosButton.setEnabled(true);
        } catch (Exception ex) {
            maisButton.setEnabled(false);
            menosButton.setEnabled(false);
        }
    }//GEN-LAST:event_listaCarrinhoValueChanged

    private void maisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisButtonActionPerformed
        try {
            int id = getIdSelecionado();
            ProdutoCarrinho produtoSelecionado = Carrinho.getProdutoCarrinho(id);
            produtoSelecionado.setQuantidade(produtoSelecionado.getQuantidade() + 1);
            quantidadeLabel.setText(String.valueOf(produtoSelecionado.getQuantidade()));
            int indexSelecionado = listaCarrinho.getSelectedIndex();
            atualizarLista();
            listaCarrinho.setSelectedIndex(indexSelecionado);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_maisButtonActionPerformed

    private void menosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosButtonActionPerformed
        try {
            int id = getIdSelecionado();
            ProdutoCarrinho produtoSelecionado = Carrinho.getProdutoCarrinho(id);
            int novaQuantidade = produtoSelecionado.getQuantidade() - 1;
            if (novaQuantidade <= 0) {
                return;
            }
            produtoSelecionado.setQuantidade(novaQuantidade);
            quantidadeLabel.setText(String.valueOf(produtoSelecionado.getQuantidade()));
            int indexSelecionado = listaCarrinho.getSelectedIndex();
            atualizarLista();
            listaCarrinho.setSelectedIndex(indexSelecionado);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_menosButtonActionPerformed

    private int getIdSelecionado() throws Exception {
        String valorSelecionado = listaCarrinho.getSelectedValue();
        int id = Integer.parseInt(valorSelecionado.substring(0, valorSelecionado.indexOf("|")).trim());
        return id;
    }

    private void atualizarLista() {
        int tamanho = Carrinho.getProdutosCarrinho().size();
        String produtosStrings[] = new String[tamanho + 1];
        
        produtosStrings[0] = String.format("%6s | %-20s | %10s | %-14s | %-11s", "Id", "Nome", "Quantidade", "Valor unitário", "Valor total");
        for (int i = 0; i < tamanho; i++) {
            produtosStrings[i + 1] = Carrinho.getProdutosCarrinho().get(i).getInfoString();
        }

        listaCarrinho.setFont(new Font("Courier New", Font.PLAIN, 11));
        listaCarrinho.setListData(produtosStrings);

        totalLabel.setText(String.format("Total: R$%-4.2f", Carrinho.getValorTotal()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton finalizarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaCarrinho;
    private javax.swing.JButton maisButton;
    private javax.swing.JButton menosButton;
    private javax.swing.JLabel quantidadeLabel;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

}
